// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_WEB'),
    appId: const String.fromEnvironment('FIREBASE_APP_ID_WEB'),
    messagingSenderId: '1061003401193',
    projectId: 'wargo-e9839',
    authDomain: 'wargo-e9839.firebaseapp.com',
    storageBucket: 'wargo-e9839.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_ANDROID'),
    appId: const String.fromEnvironment('FIREBASE_APP_ID_ANDROID'),
    messagingSenderId: '1061003401193',
    projectId: 'wargo-e9839',
    storageBucket: 'wargo-e9839.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_IOS'),
    appId: const String.fromEnvironment('FIREBASE_APP_ID_IOS'),
    messagingSenderId: '1061003401193',
    projectId: 'wargo-e9839',
    storageBucket: 'wargo-e9839.firebasestorage.app',
    iosBundleId: 'com.example.wargo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_MACOS'),
    appId: const String.fromEnvironment('FIREBASE_APP_ID_MACOS'),
    messagingSenderId: '1061003401193',
    projectId: 'wargo-e9839',
    storageBucket: 'wargo-e9839.firebasestorage.app',
    iosBundleId: 'com.example.wargo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_WINDOWS'),
    appId: const String.fromEnvironment('FIREBASE_APP_ID_WINDOWS'),
    messagingSenderId: '1061003401193',
    projectId: 'wargo-e9839',
    authDomain: 'wargo-e9839.firebaseapp.com',
    storageBucket: 'wargo-e9839.firebasestorage.app',
  );
}
