// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0KYho_quQ9ZHrEQp0z0zWbwspraJUaZ4',
    appId: '1:1061003401193:web:4eb9c8ed68e88cdb33dd78',
    messagingSenderId: '1061003401193',
    projectId: 'wargo-e9839',
    authDomain: 'wargo-e9839.firebaseapp.com',
    storageBucket: 'wargo-e9839.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5-Wle83FWzXfj4sfriLxRWF2kAU0oNq0',
    appId: '1:1061003401193:android:a241237bc958211e33dd78',
    messagingSenderId: '1061003401193',
    projectId: 'wargo-e9839',
    storageBucket: 'wargo-e9839.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuzOa5yaMomo2oc3mVQzl8I2K8orTSIxQ',
    appId: '1:1061003401193:ios:0f1004bff594e17b33dd78',
    messagingSenderId: '1061003401193',
    projectId: 'wargo-e9839',
    storageBucket: 'wargo-e9839.firebasestorage.app',
    iosBundleId: 'com.example.wargo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuzOa5yaMomo2oc3mVQzl8I2K8orTSIxQ',
    appId: '1:1061003401193:ios:0f1004bff594e17b33dd78',
    messagingSenderId: '1061003401193',
    projectId: 'wargo-e9839',
    storageBucket: 'wargo-e9839.firebasestorage.app',
    iosBundleId: 'com.example.wargo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0KYho_quQ9ZHrEQp0z0zWbwspraJUaZ4',
    appId: '1:1061003401193:web:ed49a664b08eef5533dd78',
    messagingSenderId: '1061003401193',
    projectId: 'wargo-e9839',
    authDomain: 'wargo-e9839.firebaseapp.com',
    storageBucket: 'wargo-e9839.firebasestorage.app',
  );
}
